version = 0.1

[default.deploy.parameters]
stack_name = "mafioso-backend-new"
resolve_s3 = true
s3_prefix = "mafioso-backend"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\" WorldIdAppId=\"app_bc75ea0f4623eb64e1814126df474de3\" JWTSecretArn=\"arn:aws:secretsmanager:eu-west-2:152034782674:secret:Mafioso_JWT-rY4ENa\" WorldIdSecretArn=\"arn:aws:secretsmanager:eu-west-2:152034782674:secret:Mafioso_APIKey-o92Bbh\""
image_repositories = []
