AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mafioso - Backend API and Database Infrastructure

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        PLAYERS_TABLE: !Ref PlayersTable
        WORLD_ID_TABLE: !Ref WorldIdTable
        NONCES_TABLE: !Ref NoncesTable
        COOLDOWNS_TABLE: !Ref CooldownsTable
        CRIME_HISTORY_TABLE: !Ref CrimeHistoryTable
        JWT_SECRET_ARN: !Ref JWTSecretArn
        WORLD_ID_SECRET_ARN: !Ref WorldIdSecretArn
        WORLD_ID_APP_ID: !Ref WorldIdAppId

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment stage
  
  JWTSecretArn:
    Type: String
    Description: ARN of the JWT secret in AWS Secrets Manager
    Default: ""
  
  WorldIdSecretArn:
    Type: String
    Description: ARN of the World ID API key secret in AWS Secrets Manager
    Default: ""
  
  WorldIdAppId:
    Type: String
    Description: World ID App ID
    Default: app_bc75ea0f4623eb64e1814126df474de3

Resources:
  # API Gateway
  MafiosoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # Lambda Functions
  VerifyWorldIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/functions/auth/
      Handler: verifyWorldId.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref WorldIdTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref JWTSecretArn
                - !Ref WorldIdSecretArn
      Events:
        VerifyWorldId:
          Type: Api
          Properties:
            RestApiId: !Ref MafiosoApi
            Path: /auth/verify-worldid
            Method: post

  VerifyMiniKitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/functions/auth/
      Handler: verifyMiniKit.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref WorldIdTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref JWTSecretArn
                - !Ref WorldIdSecretArn
      Events:
        VerifyMiniKit:
          Type: Api
          Properties:
            RestApiId: !Ref MafiosoApi
            Path: /auth/verify-minikit
            Method: post

  NonceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/functions/auth/
      Handler: nonce.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NoncesTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref JWTSecretArn
                - !Ref WorldIdSecretArn
      Events:
        GetNonce:
          Type: Api
          Properties:
            RestApiId: !Ref MafiosoApi
            Path: /auth/nonce
            Method: get

  WalletLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/functions/auth/
      Handler: walletLogin.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NoncesTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref JWTSecretArn
                - !Ref WorldIdSecretArn
      Events:
        WalletLogin:
          Type: Api
          Properties:
            RestApiId: !Ref MafiosoApi
            Path: /auth/wallet-login
            Method: post

  CreateAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/functions/auth/
      Handler: createAccount.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayersTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref JWTSecretArn
                - !Ref WorldIdSecretArn
      Events:
        CreateAccount:
          Type: Api
          Properties:
            RestApiId: !Ref MafiosoApi
            Path: /auth/create-account
            Method: post

  CheckUsernameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/functions/auth/
      Handler: checkUsername.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayersTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref JWTSecretArn
                - !Ref WorldIdSecretArn
      Events:
        CheckUsername:
          Type: Api
          Properties:
            RestApiId: !Ref MafiosoApi
            Path: /auth/check-username
            Method: get

  ValidateTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/functions/auth/
      Handler: validateToken.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayersTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref JWTSecretArn
                - !Ref WorldIdSecretArn
      Events:
        ValidateToken:
          Type: Api
          Properties:
            RestApiId: !Ref MafiosoApi
            Path: /auth/validate
            Method: get

  # DynamoDB Tables
  PlayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mafioso-${Stage}-players'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: walletAddress
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: walletAddress
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: username-index
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  WorldIdTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mafioso-${Stage}-worldid'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: nullifierHash
          AttributeType: S
      KeySchema:
        - AttributeName: nullifierHash
          KeyType: HASH

  NoncesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mafioso-${Stage}-nonces'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: nonce
          AttributeType: S
      KeySchema:
        - AttributeName: nonce
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  CooldownsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mafioso-${Stage}-cooldowns'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S
        - AttributeName: crimeId
          AttributeType: N
      KeySchema:
        - AttributeName: playerId
          KeyType: HASH
        - AttributeName: crimeId
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  CrimeHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mafioso-${Stage}-crime-history'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${MafiosoApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'