AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mafioso - Backend API and Database Infrastructure

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        PLAYERS_TABLE: !Ref PlayersTable
        WORLD_ID_TABLE: !Ref WorldIdTable
        COOLDOWNS_TABLE: !Ref CooldownsTable
        CRIME_HISTORY_TABLE: !Ref CrimeHistoryTable
        JWT_SECRET: !Ref JWTSecret

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment stage
  
  JWTSecret:
    Type: String
    NoEcho: true
    Description: JWT signing secret
    Default: mafioso-dev-secret-change-in-production
  
  WorldIdAppId:
    Type: String
    Description: World ID App ID
    Default: app_staging_123456789

Resources:
  # API Gateway
  MafiosoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # Lambda Functions
  VerifyWorldIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/functions/auth/
      Handler: verifyWorldId.handler
      Environment:
        Variables:
          WORLD_ID_APP_ID: !Ref WorldIdAppId
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref WorldIdTable
      Events:
        VerifyWorldId:
          Type: Api
          Properties:
            RestApiId: !Ref MafiosoApi
            Path: /auth/verify-worldid
            Method: post

  # DynamoDB Tables
  PlayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mafioso-${Stage}-players'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: worldId
          AttributeType: S
      KeySchema:
        - AttributeName: worldId
          KeyType: HASH

  WorldIdTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mafioso-${Stage}-worldid'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: nullifierHash
          AttributeType: S
      KeySchema:
        - AttributeName: nullifierHash
          KeyType: HASH

  CooldownsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mafioso-${Stage}-cooldowns'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S
        - AttributeName: crimeId
          AttributeType: N
      KeySchema:
        - AttributeName: playerId
          KeyType: HASH
        - AttributeName: crimeId
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  CrimeHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'mafioso-${Stage}-crime-history'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${MafiosoApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'